# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- staging
- qa
- develop

pool:
  vmImage: ubuntu-latest #windows-2019

steps:
- checkout: self
  persistCredentials: true

- script: |
    echo "##vso[task.setvariable variable=tag_version]V20-PRUEBA"
    echo "##vso[task.setvariable variable=rama]$(Build.SourceBranchName)"
- task: ManualValidation@0
  displayName: Solicitar aprobación manual en master
  inputs:
    notifyUsers: |
      diegodlrh@hotmail.com
      ignacio.eat@gmail.com
    instructions: 'Aprobar nueva versión de build ($(tag_version)) para orders en rama $(rama). De no aprobarla en 24hrs se cancelará este pipeline.'
  condition: and(succeeded(), eq(variables['rama'], 'master')) 

- script: echo "ESTOY EN EL ECHOOOOOOOO"
  

#steps:
#- powershell: Write-Host  "##vso[task.setvariable variable=rama;isOutput=true]$(Build.SourceBranchName)"
#    - script: echo  "##vso[task.setvariable variable=rama;isOutput=true]$(Build.SourceBranchName)"

#    - task: TriggerPipeline@2
#      inputs:
#        serviceConnection: 'Nuevo conector con azure devops api'
#        project: '5bbf4689-b099-4048-ac8d-75991900f2f0'
#        Pipeline: 'Build'
#        buildDefinition: '21'
#        Branch: 'pipelines_ci'
#        buildapiversion: '6.0'
    
    