# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- staging
- qa
- develop

pool:
  vmImage: ubuntu-latest #windows-2019


jobs:
     
- job: ci
  displayName: ETAPA CI
  steps:
  - checkout: self
    persistCredentials: true

  - bash: | 
      echo "##vso[task.setvariable variable=rama;isoutput=true]master"
      echo "##vso[task.setvariable variable=version;isoutput=true]v233prueba"   
    name: setVars

  - bash: |
      echo "tag es $(setVars.version)"
      echo "rama es $(setVars.rama)"

- job: esperarValidacion
  displayName: Wait for external validation
  pool: server
  dependsOn: ci
  variables:
    version: $[ dependencies.ci.outputs['setVars.version'] ]  
    rama: $[ dependencies.ci.outputs['setVars.rama'] ]  

  timeoutInMinutes: 4320 # job times out in 3 days
  steps:
  - task: ManualValidation@0
    timeoutInMinutes: 1440 # task times out in 1 day
    inputs:
      notifyUsers:  |
        diegodlrh@hotmail.com
#        ignacio.eat@gmail.com
      instructions: 'Aprobar nueva versión de build ($(version)) para orders en rama $(rama). De no aprobarla en 24hrs se cancelará este pipeline.'
      onTimeout: 'reject'
    condition: eq($(rama), 'pp')
  


- job: 
  displayName: ETAPA CD
  dependsOn: 
    - ci
    - esperarValidacion
  variables:
    version: $[ dependencies.ci.outputs['setVars.tag_version'] ]  
    rama: $[ dependencies.ci.outputs['setVars.rama'] ]  
  steps:
  - script: echo "ESTOY EN EL ECHOOOOOOOO $(version) $(rama)"
  

#steps:
#- powershell: Write-Host  "##vso[task.setvariable variable=rama;isOutput=true]$(Build.SourceBranchName)"
#    - script: echo  "##vso[task.setvariable variable=rama;isOutput=true]$(Build.SourceBranchName)"

#    - task: TriggerPipeline@2
#      inputs:
#        serviceConnection: 'Nuevo conector con azure devops api'
#        project: '5bbf4689-b099-4048-ac8d-75991900f2f0'
#        Pipeline: 'Build'
#        buildDefinition: '21'
#        Branch: 'pipelines_ci'
#        buildapiversion: '6.0'
    
    