# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
#- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

pool:
  vmImage: ubuntu-latest

# instalar docer cli

 - task: DockerInstaller@0
   inputs:
     dockerVersion: '17.09.0-ce'

# buildiar la imagen


  - task: Docker@1
    displayName: Realizar build de imagen docker
    inputs:
      command: 'Build an image'
      dockerFile: '**/Dockerfile'
      #arguments: '--build-arg JAR_FILE=target/products-service-example-0.0.1-SNAPSHOT.jar'
      imageName: 'products-service'

- script: docker run -d --name products-service-test products-service
  displayName: Levantar docker 

- script: docker inspect products-service-test | grep '"IPAddress":' -A 0 -m 1 | cut -f4 -d'"' 
  displayName: Obtener ip del docker MS

- script: docker ps -a
  displayName: Verificar dockers levantados
